#!/bin/bash
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##

TITLE="<b>Copiar ruta</b>"

ME=${0##*/}

showHelp() {
    cat >&2 <<EOF
Uso: ${ME} RUTA
Copia la ruta de ficheros y directorios a la cola de Klipper
EOF
    exit 0
}

isExecutable() {
    type -p "$1" &>/dev/null || return 1
}

ret=0
arg=${1,,}
[[ $arg == -h || $arg == --help ]] && showHelp

if [[ -z $KDE_FULL_SESSION ]]; then
    notify-send -i "dialog-error" "$TITLE" "No hay una sesión con KDE como escritorio." -t 10000
    exit 64
fi

if (( $(pgrep -c dolphin) )); then
    if (( $# )); then
        arg=$(realpath -m -- "$1")
        if isExecutable xclip; then
            printf "$arg" | xclip -in -selection clipboard
            ret=$?
        elif isExecutable xsel; then
            printf "$arg" | xsel --input --clipboard
        else
            notify-send \
                -i "dialog-error" \
                "$TITLE" \
                "No se pudo copiar el texto al portapapeles." \
                -t 10000
            ret=1
        fi
    else
        notify-send -i "dialog-warning" "$TITLE" "Sin nada para copiar..." -t 10000
        ret=2
    fi
else
    notify-send -i "dialog-error" "$TITLE" "Dolphin no está activo." -t 10000
    ret=32
fi

exit $ret

